# 完整Lint支持列表 https://dart-lang.github.io/linter/lints/
linter:
  rules:
    # 声明方法总是返回类型
    - always_declare_return_types
    # 结构体总在新行
    - always_put_control_body_on_new_line
    # 必要参数总在最前
    - always_put_required_named_parameters_first
    # 总是验证必要参数非null
    - always_require_non_null_named_parameters
    # - always_specify_types
    # 强制 override 注解
    - annotate_overrides
    # - avoid_annotating_with_dynamic
    # 避免使用 as
    - avoid_as
    # 避免在表达式使用 bool
    - avoid_bool_literals_in_conditional_expressions
    # 禁止无约束捕获异常
    - avoid_catches_without_on_clauses
    # 禁止捕获Error
    - avoid_catching_errors
    # 禁止类中定义静态成员
    - avoid_classes_with_only_static_members
    # - avoid_double_and_int_checks
    # 禁止空 else 结构体
    - avoid_empty_else
    # 对于 const 使用 get 减少无用成员变量, !!! JS不能遵循
    - avoid_field_initializers_in_const_classes
    # 不要使用 foreach 作为 function literal
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    # 禁止重载 == 时进行 null 检查
    - avoid_null_checks_in_equality_operators
    # 禁止无名称 bool 参数
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    # 禁止相对路径导包
    - avoid_relative_lib_imports
    # 禁止重写方法重命名参数名
    - avoid_renaming_method_parameters
    # 禁止 set 方法有返回类型
    - avoid_return_types_on_setters
    # 禁止返回 null
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    # 禁止返回 this
    - avoid_returning_this
    # 禁止定义 set 无 get
    - avoid_setters_without_getters
    # 避免阴影类型
    - avoid_shadowing_type_parameters
    # 禁止单个级联调用
    - avoid_single_cascade_in_expression_statements
    # 禁止低速IO操作
    - avoid_slow_async_io
    # 禁止将类型名作为参数名
    - avoid_types_as_parameter_names
    # 禁止给函数表达式添加类型声明, 可自动类型推断
    - avoid_types_on_closure_parameters
    # 构造方法禁止定义不使用的参数
    - avoid_unused_constructor_parameters
    # 禁止无返回值的 async 方法
    - avoid_void_async
    # await 必须使用 Future,保证向后兼容
    - await_only_futures
    # 类型驼峰命名
    - camel_case_types
    # 必须取消 StreamSubscription
    - cancel_subscriptions
    # 必须使用级联进行连续调用
    - cascade_invocations
    # 必须关闭 sinks
    - close_sinks
    # 保证文档链接有效
    - comment_references
    # 小写常量名
    # - constant_identifier_names
    # 禁止在 finally 使用控制逻辑
    - control_flow_in_finally
    # 结构体必须使用 {}
    - curly_braces_in_flow_control_structures
    # 导包排序
    - directives_ordering
    # 禁止空 catche
    - empty_catches
    # 空构造方法使用 ; 而不是 {}
    - empty_constructor_bodies
    # 禁止空语句
    - empty_statements
    # 文件使用 下划线命名法
    - file_names
    # 使用 Flutter 风格 TODO
    - flutter_style_todos
    # 如果重写 hashCode 必须重写 == 操作符, 反之亦然
    - hash_and_equals
    # 禁止导入其他库实现细节文件
    - implementation_imports
    # 不要添加无效的 bool 判断
    - invariant_booleans
    # 禁止使用 contains 判断和 Iterable 不同的参数类型
    - iterable_contains_unrelated_type
    # 可能时合并返回体
    - join_return_with_assignment
    # 库名使用 下划线命名法
    - library_names
    # 使用 下划线命名法 导库
    - library_prefixes
    # 行宽80字符
    # - lines_longer_than_80_chars
    # 禁止使用 remove 删除和 Iterable 不同的参数类型
    - list_remove_unrelated_type
    # 禁止条件判断编译时固定的 bool
    - literal_only_boolean_expressions
    # 不要在list定义时使用相邻字符串,使用 +
    - no_adjacent_strings_in_list
    # 不要使用多个相同的 case 值
    - no_duplicate_case_values
    # 使用小驼峰命名 变量
    - non_constant_identifier_names
    # 禁止使用 null 作为某些系统函数的参数传递, https://dart-lang.github.io/linter/lints/null_closures.html
    - null_closures
    # 可推断的局部类型定义可以省略
    - omit_local_variable_types
    # 使用 typedef 定义只有一个方法的抽象类(接口)
    - one_member_abstracts
    # 只允许 throw Error 和 Exception
    - only_throw_errors
    # 不允许重写变量
    # - overridden_fields
    # 给所有公共APIs添加文档
    - package_api_docs
    # 包名使用 下划线命名法
    - package_names
    # 库名包名前缀
    - package_prefixed_library_names
    # 禁止为方法参数分配新值
    - parameter_assignments
    # 使用相邻字符串连接
    - prefer_adjacent_string_concatenation
    # TODO 需要更多 simple
    # - prefer_asserts_in_initializer_lists
    # 如果可能使用 collection literals
    - prefer_collection_literals
    # 使用 ??= 判 null
    - prefer_conditional_assignment
    # 使用 const 实例化常量
    - prefer_const_constructors
    # 推荐对 @immutable 类使用 const 定义构造函数
    - prefer_const_constructors_in_immutables
    # 推荐使用 const , const 对热加载更加友好
    - prefer_const_declarations
    # 使用 const 实例化 list 和 map 作为函数的不可变参数 
    - prefer_const_literals_to_create_immutables
    # 推荐使用构造方法而不是静态方法构造实例
    - prefer_constructors_over_static_methods
    # 推荐使用 contains 而不是 indexOf
    - prefer_contains
    # 推荐使用 = 分隔参数和默认值
    - prefer_equal_for_default_values
    # 使用 => 缩短单个返回
    - prefer_expression_function_bodies
    # 推荐使用 final 定义私有变量
    - prefer_final_fields
    # 再 for-each 中，如果未重新定义，推荐使用 final
    - prefer_final_in_for_each
    # 对于局部变量，如果未重新定义，推荐使用 final
    - prefer_final_locals
    # 给所有元素应用某个方法，推荐使用 foreach 
    - prefer_foreach
    # 使用函数声明为函数添加名称
    - prefer_function_declarations_over_variables
    # 推荐使用 通用函数类型别名 而不是 函数类型别名
    - prefer_generic_function_type_aliases
    # 尽可能使用 initializing formals 是初始化更简单
    - prefer_initializing_formals
    # 数字可读性展示
    - prefer_int_literals
    # 使用插值定于文字
    - prefer_interpolation_to_compose_strings
    # 不要使用 length 判断集合为空
    - prefer_is_empty
    # 不要使用 !x.isEmpty 判断集合不为空
    - prefer_is_not_empty
    # 推荐使用 iterable.whereType<T>() 而不是 iterable.where((e) => e is T) 判断类型
    - prefer_iterable_whereType
    # 推荐使用 mixin
    - prefer_mixin
    # 推荐使用 ?. 空检查
    - prefer_null_aware_operators
    # 在不需要转义是使用单引号
    - prefer_single_quotes
    # 为未初始化变量指定类型
    - prefer_typing_uninitialized_variables
    # 推荐使用 void 而不是 Null
    - prefer_void_to_null
    # 在 Deprecation 说明弃用内容
    # - provide_deprecation_message
    # 所有公共成员添加文档
    # - public_member_api_docs
    # 不要递归 get
    - recursive_getters
    # 推荐使用 /// 而不是 /** 添加文档注释
    - slash_for_doc_comments
    # 构造函数在所有函数之前
    - sort_constructors_first
    # 对pub依赖排序
    - sort_pub_dependencies
    # 构造函数在所有函数之前
    - sort_unnamed_constructors_first
    # 在 == 中 判断类型
    - test_types_in_equals
    # 避免在 finally 中抛出异常
    - throw_in_finally
    # 为公共API方法明确传入类型
    - type_annotate_public_apis
    # 如果构造方法存在初始化字段，不用声明参数类型
    - type_init_formals
    # 使用 unawaited 忽略 Future 返回
    - unawaited_futures
    # 除非必要不要返回 await
    - unnecessary_await_in_return
    # 避免在不需要时使用 {} 插值
    # - unnecessary_brace_in_string_interps
    # 避免重复定义 const
    - unnecessary_const
    # 避免不需要的 get set
    - unnecessary_getters_setters
    # 避免不必要的 lamdba
    - unnecessary_lambdas
    # 不要使用 new 关键字
    - unnecessary_new
    # 避免在 null-aware 中使用 null
    - unnecessary_null_aware_assignments
    # 在 if null 操作符中使用 null
    - unnecessary_null_in_if_null_operators
    # 避免无效的重写
    - unnecessary_overrides
    # 不要使用无效的 ()
    - unnecessary_parenthesis
    # 避免不必要的语句
    - unnecessary_statements
    # 避免不必要的 this
    - unnecessary_this
    # 不要比较无关类型相等
    - unrelated_type_equality_checks
    # 使用 argb 声明颜色
    - use_full_hex_values_for_flutter_colors
    # 对参数类型使用范型方法
    - use_function_type_syntax_for_parameters
    # 如果可能使用 rethrow 抛出异常
    - use_rethrow_when_possible
    # 使用 setter 进行属性修改
    - use_setters_to_change_properties
    # 使用 StringBuffer 拼接字符
    - use_string_buffers
    # 使用 toXXX asXXX进行类型转换
    - use_to_and_as_if_applicable
    # 校验正则
    - valid_regexps
    # 检查 void 无效使用
    - void_checks
  